name: GeospatialPyContainer
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - numpy
  - pandas
  - rasterio
  - xarray
  - rioxarray
  - pip
  - ipykernel
  - ipython
  - jupyter
  - matplotlib
  - pip:

